name: test

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - test/smoke
  push:
    branches:
      - main
      - test/smoke
    paths-ignore:
      - docs/**
  workflow_dispatch:

jobs:
  check-label:
    runs-on: ubuntu-22.04
    outputs:
      run_smoke_tests: ${{ steps.check.outputs.run_smoke_tests }}
    steps:
      - name: Check if PR author is a member of the organization or has the run-smoke label
        id: check
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "run_smoke_tests=true" >> $GITHUB_ENV
            exit 0
          fi

          ORG="gptscript-ai"
          USERNAME="${{ github.event.pull_request.user.login }}"
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/orgs/$ORG/members/$USERNAME")

          if [ "$RESPONSE" != "{}" ]; then
            echo "run_smoke_tests=true" >> $GITHUB_ENV
            exit 0
          fi

          LABELS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/issues/${{ github.event.pull_request.number }}/labels" | jq -r '.[].name')

          if echo "$LABELS" | grep -q "run-smoke"; then
            echo "run_smoke_tests=true" >> $GITHUB_ENV
            exit 0
          fi

          echo "run_smoke_tests=false" >> $GITHUB_ENV

  smoke-gpt-4o-2024-05-13:
    needs: check-label
    if: ${{ needs.check-label.outputs.run_smoke_tests == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Checkout PR code if running for a PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "1.21"
      - env:
          OPENAI_API_KEY: ${{ secrets.SMOKE_OPENAI_API_KEY }}
          GPTSCRIPT_DEFAULT_MODEL: gpt-4o-2024-05-13
        name: Run smoke test for gpt-4o-2024-05-13
        run: |
          echo "Running smoke test for model gpt-4o-2024-05-13"
          make smoke

  smoke-gpt-4-turbo-2024-04-09:
    needs: check-label
    if: ${{ needs.check-label.outputs.run_smoke_tests == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Checkout PR code if running for a PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "1.21"
      - env:
          OPENAI_API_KEY: ${{ secrets.SMOKE_OPENAI_API_KEY }}
          GPTSCRIPT_DEFAULT_MODEL: gpt-4-turbo-2024-04-09
        name: Run smoke test for gpt-4-turbo-2024-04-09
        run: |
          echo "Running smoke test for model gpt-4-turbo-2024-04-09"
          make smoke

  smoke-claude-3-opus-20240229:
    needs: check-label
    if: ${{ needs.check-label.outputs.run_smoke_tests == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Checkout PR code if running for a PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "1.21"
      - env:
          OPENAI_API_KEY: ${{ secrets.SMOKE_OPENAI_API_KEY }}
          GPTSCRIPT_DEFAULT_MODEL: claude-3-opus-20240229 from github.com/gptscript-ai/claude3-anthropic-provider@tool-beta
          ANTHROPIC_API_KEY: ${{ secrets.SMOKE_ANTHROPIC_API_KEY }}
        name: Run smoke test for claude-3-opus-20240229
        run: |
          echo "Running smoke test for model claude-3-opus-20240229"
          make smoke

  smoke-mistral-large-2402:
    needs: check-label
    if: ${{ needs.check-label.outputs.run_smoke_tests == 'true' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout base repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Checkout PR code if running for a PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: "1.21"
      - env:
          OPENAI_API_KEY: ${{ secrets.SMOKE_OPENAI_API_KEY }}
          GPTSCRIPT_DEFAULT_MODEL: mistral-large-2402 from https://api.mistral.ai/v1
          GPTSCRIPT_PROVIDER_API_MISTRAL_AI_API_KEY: ${{ secrets.SMOKE_GPTSCRIPT_PROVIDER_API_MISTRAL_AI_API_KEY }}
        name: Run smoke test for mistral-large-2402
        run: |
          echo "Running smoke test for model mistral-large-2402"
          make smoke

